[37;1m2024-10-18 12:25:25.251 [31;1m[[37;1mRTPS_TRANSPORT_SHM[31;1m Error] [37mFailed init_port fastrtps_port7411: open_and_lock_file failed[34;1m -> Function [36mopen_port_internal[m
/peanut_butter_falcon_quote_publisher_node:
  ros__parameters:
    period: 0.25
    philosopher_name: Tyler
    quote: You got a good-guy heart. You can't do shit about it, that's just who you
      are. You're a hero
    topic_name: truly_inspirational_quote
    use_sim_time: false

