<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ada_lovelace">

<xacro:property name="chassis_diameter" value="0.350" />
<xacro:property name="chassis_height" value="0.080" />
<xacro:property name="lidar_diameter" value="0.070" />
<xacro:property name="lidar_height" value="0.030" />
<xacro:property name="wheel_diameter" value="0.080" />
<xacro:property name="wheel_distance" value="0.260" />
<xacro:property name="wheel_thickness" value="0.020" />
<xacro:property name="castor_distance" value="0.290" />
<xacro:property name="castor_diameter" value="0.010" />
<xacro:property name="ground_clearance" value="0.005" />
<xacro:property name="camera_width" value="0.080" />
<xacro:property name="camera_height" value="0.016" />
    
<xacro:include filename="$(find ada_lovelace_description)/urdf/gazebo.xacro"/>

    <!-- LINKS -->

    <link name="base_footprint_link" />

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${chassis_diameter/2}" length="${chassis_height}"/>
            </geometry> 
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="white">
                <color rgba="1 1 1 1" />
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${chassis_diameter/2}" length="${chassis_height}"/>
            </geometry> 
            <origin rpy = "0 0 0" xyz="0 0 0" />
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="4.2" />
        </inertial>
    </link>

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_diameter/2}" length="${lidar_height}" />
            </geometry>
        
            <origin rpy="0 0 0" xyz="0 0 0" />

            <material name="red">
                <color rgba="1 0 0 1" />
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${lidar_diameter/2}" length="${lidar_height}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>

        <inertial>
            <mass value="0.20" />
        </inertial>
    </link>

    <link name="wheel_left_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="wheel_thickness" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="blue">
                <color rgba="0.1 0.1 0.8 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="wheel_thickness" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        
        <inertial>
            <mass value="0.10" />
        </inertial>
    </link>

    <link name="wheel_right_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="wheel_thickness" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="blue">
                <color rgba="0.1 0.1 0.8 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="wheel_thickness" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        
        <inertial>
            <mass value="0.10" />
        </inertial>
    </link>

    <link name="front_ball_castor_link">
        <visual>
            <geometry>
                <sphere radius="${castor_diameter/2}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0.1 0.1 0.8 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${castor_diameter/2}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
            <mass value="0.06"/>
        </inertial>
    </link>

    <link name="rear_ball_castor_link">
        <visual>
            <geometry>
                <sphere radius="${castor_diameter/2}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0.1 0.1 0.8 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${castor_diameter/2}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
            <mass value="0.06"/>
        </inertial>
    </link>

    <link name="imu_link">
        
    </link>

    <link name="chassis_link">

    </link>

    <link name="depth_camera_link">
        <visual>
            <geometry>
                <box size="${camera_height} ${camera_width} ${camera_height}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="green">
                <color rgba="0 1 0 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <box size="${camera_height} ${camera_width} ${camera_height}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
            <mass value="0.08"/>
        </inertial>
    </link>

    <!-- JOINTS -->

    <joint name="base_footprint_link_base_link_joint" type="fixed">
        <parent link="base_footprint_link"/>
        <child link="base_link"/>
        
        <origin xyz="0 0 ${ground_clearance}" rpy="0 0 0" />
    </joint>

    <joint name="base_link_left_wheel_link_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>

        <origin xyz="0 ${wheel_distance/2} 0.035" rpy="0 0 0" /> 
    </joint>

    <joint name="base_link_right_wheel_link_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>

        <origin xyz="0 -${wheel_distance/2} 0.035" rpy="0 0 0" /> 
    </joint>

    <joint name="base_link_front_ball_castor_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_ball_castor_link"/>

        <origin xyz="${castor_distance/2} 0 ${ground_clearance}" rpy="0 0 0" />
    </joint>

    <joint name="base_link_rear_ball_castor_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_ball_castor_link"/>

        <origin xyz="-${castor_distance/2} 0 ${ground_clearance}" rpy="0 0 0" />
    </joint>

    <joint name="base_link_chassis_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        
        <origin xyz="0 0 ${ground_clearance}+${chassis_height/2}" rpy="0 0 0" />
    </joint>


</robot>