<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- GAZEBO PLUGINS -->

  <!-- Differential Drive -->
  <gazebo>
    <plugin filename="ignition-gazebo-diff-drive-system" name="ignition::gazebo::systems::DiffDrive">
      <!-- Wheel Joints -->
      <left_joint>base_link_left_wheel_link_joint</left_joint>
      <right_joint>base_link_right_wheel_link_joint</right_joint>

      <!-- Kinematics -->
      <wheel_separation>${wheel_distance}</wheel_separation>
      <wheel_radius>${wheel_diameter/2}</wheel_radius>
      <min_linear_velocity>-1.2</min_linear_velocity>
      <max_linear_velocity>1.2</max_linear_velocity>
      <min_angular_velocity>-3.14159</min_angular_velocity>
      <max_angular_velocity>3.14159</max_angular_velocity>

      <odom_publish_frequency>100</odom_publish_frequency>

      <!-- TF Frames -->
      <frame_id>/odom</frame_id>
      <child_frame_id>/base_footprint_link</child_frame_id>

      <!-- Topics -->
      <!-- <odom_topic>/model/ada_lovelace/odometry</odom_topic> -->
    </plugin>
  </gazebo>

  <!-- Joint State Publisher -->
  <gazebo>
    <plugin filename="ignition-gazebo-joint-state-publisher-system" name="ignition::gazebo::systems::JointStatePublisher">
      <update_rate>100</update_rate>
      <joint_name>base_link_right_wheel_link_joint</joint_name>
      <joint_name>base_link_left_wheel_link_joint</joint_name>
      <topic>/model/ada_lovelace/joint_state</topic>
    </plugin>
  </gazebo>

  <!-- SENSORS -->

  <!-- LiDAR -->
  <gazebo reference="lidar_link">
    <sensor type="gpu_lidar" name="generic_lidar_sensor">
      <topic>/model/ada_lovelace/scan</topic>
      <frame_id>lidar_link</frame_id>
      <ignition_frame_id>lidar_link</ignition_frame_id>
      <update_rate>10.0</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>1024</samples>
            <resolution>1</resolution>
            <min_angle>-${pi*0.75}</min_angle>
            <max_angle>${pi*0.75}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>20.0</max>
          <resolution>0.03</resolution>
        </range>
      </ray>
      <always_on>1</always_on>
      <visualize>true</visualize>
    </sensor>
  </gazebo>
  

  <!-- IMU -->
  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <topic>/model/ada_lovelace/imu</topic>
      <frame_id>imu_link</frame_id>
      <ignition_frame_id>imu_link</ignition_frame_id>
      <plugin filename="libignition-gazebo-imu-system.so" name="ignition::gazebo::systems::Imu">
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
      </plugin>
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
    </sensor>
  </gazebo>
  <gazebo>
    <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
  </gazebo>

  <!-- Depth Camera -->
  <gazebo reference="depth_camera_link">
    <sensor type="camera" name="depth_camera">
      <topic>/model/ada_lovelace/depth</topic>
      <frame_id>depth_camera_link</frame_id>
      <ignition_frame_id>depth_camera_link</ignition_frame_id>
      <update_rate>60</update_rate>
      <camera>
        <horizontal_fov>1.51844</horizontal_fov>
        <vertical_fov>1.01229</vertical_fov>
        <image>
          <width>1280</width>
          <height>720</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.3</near>
          <far>4.0</far>
        </clip>
      </camera>
      <always_on>1</always_on>
      <!-- <plugin name="gazebo_ros_camera" filename="libgazebo_ros_camera.so">
        <robotNamespace>/ada_lovelace</robotNamespace>
        <imageTopicName>/depth_camera/image_raw</imageTopicName>
        <cameraInfoTopicName>/depth_camera/camera_info</cameraInfoTopicName>
        <frameName>depth</frameName>
      </plugin> -->
    </sensor>
  </gazebo>

  <!-- FRICTION AND PHYSICS -->
  <gazebo reference="front_ball_castor_link">
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </gazebo>

  <gazebo reference="rear_ball_castor_link">
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </gazebo>

  <gazebo reference="base_link_right_wheel_link_joint">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
  </gazebo>

  <gazebo reference="base_link_left_wheel_link_joint">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
  </gazebo>

</robot>
